# ============================================================
#  ExplorerRefresh.ps1 - Tells Windows the icons changed
#  Uses the proper Shell API: SHChangeNotify(SHCNE_ASSOCCHANGED)
#  which refreshes desktop, Explorer windows and Start Menu icons
#  without killing explorer.exe.
# ============================================================

function Initialize-ShellApi {
    if (-not ('Win32.NativeShell' -as [type])) {
        Add-Type -Namespace Win32 -Name NativeShell -MemberDefinition @'
[DllImport("shell32.dll", SetLastError = true)]
public static extern void SHChangeNotify(int wEventId, uint uFlags, IntPtr dwItem1, IntPtr dwItem2);
'@
    }
}

function Update-ExplorerIcons {
    <#
        SHCNE_ASSOCCHANGED (0x08000000) + SHCNF_IDLIST (0x0000)
        forces the shell to rebuild its icon associations, which
        refreshes desktop, open Explorer windows and pinned/Start
        Menu shortcut icons. Also asks Windows' built-in icon helper
        (ie4uinit) to rebuild, which is more reliable for shortcut
        icons than SHChangeNotify alone.
    #>
    try {
        Initialize-ShellApi
        $SHCNE_ASSOCCHANGED = 0x08000000
        $SHCNF_IDLIST       = [uint32]0x0000
        [Win32.NativeShell]::SHChangeNotify($SHCNE_ASSOCCHANGED, $SHCNF_IDLIST, [IntPtr]::Zero, [IntPtr]::Zero)
        # ie4uinit rebuilds the per-user icon cache without killing Explorer.
        try { Start-Process -FilePath 'ie4uinit.exe' -ArgumentList '-show' -WindowStyle Hidden -ErrorAction SilentlyContinue } catch { }
        Write-Log 'Explorer icon refresh broadcast sent (SHChangeNotify + ie4uinit).' 'OK'
    } catch {
        Write-Log "Explorer refresh failed: $($_.Exception.Message). Icons will refresh after the next sign-in." 'WARN'
    }
}

function Restart-Explorer {
    <#
        The only fully reliable way to force Windows to drop cached
        shortcut icons is to restart the Explorer shell process.
        Windows automatically relaunches Explorer, so the taskbar
        briefly disappears and returns. Used to force a full icon
        refresh when clearing the icon cache.
        Returns $true if a restart was attempted.
    #>
    try {
        # Clear the (now unlocked once Explorer stops) icon cache files,
        # then stop Explorer; Windows relaunches it automatically.
        $localApp = [Environment]::GetFolderPath('LocalApplicationData')
        Stop-Process -Name 'explorer' -Force -ErrorAction SilentlyContinue
        Start-Sleep -Milliseconds 400
        $explorerCache = Join-Path $localApp 'Microsoft\Windows\Explorer'
        if (Test-Path $explorerCache) {
            foreach ($f in @(Get-ChildItem -Path $explorerCache -Filter 'iconcache*.db' -File -Force -ErrorAction SilentlyContinue)) {
                try { Remove-Item -LiteralPath $f.FullName -Force -ErrorAction SilentlyContinue } catch { }
            }
        }
        $legacy = Join-Path $localApp 'IconCache.db'
        if (Test-Path $legacy) { try { Remove-Item -LiteralPath $legacy -Force -ErrorAction SilentlyContinue } catch { } }
        # Make sure Explorer is running again (it usually auto-restarts).
        Start-Sleep -Milliseconds 300
        if (-not (Get-Process -Name 'explorer' -ErrorAction SilentlyContinue)) {
            Start-Process 'explorer.exe' -ErrorAction SilentlyContinue
        }
        Write-Log 'Explorer restarted to force icon refresh.' 'OK'
        return $true
    } catch {
        Write-Log "Explorer restart failed: $($_.Exception.Message)" 'WARN'
        try { Start-Process 'explorer.exe' -ErrorAction SilentlyContinue } catch { }
        return $false
    }
}

function Repair-IconCache {
    <#
        Rebuilds the Windows icon cache. Useful when icons appear
        blank or stale after changes. Clears the IconCache database
        files and notifies the shell. Explorer is gently restarted
        only if needed. Returns $true on success.

        SAFE: only deletes icon-cache DB files (regenerated by Windows
        automatically); never touches user data.
    #>
    try {
        $localApp = [Environment]::GetFolderPath('LocalApplicationData')
        $explorerCache = Join-Path $localApp 'Microsoft\Windows\Explorer'

        # Notify shell of an icon settings change first (often enough).
        try { Update-ExplorerIcons } catch { }

        $deleted = 0
        if (Test-Path $explorerCache) {
            foreach ($f in @(Get-ChildItem -Path $explorerCache -Filter 'iconcache*.db' -File -Force -ErrorAction SilentlyContinue)) {
                try { Remove-Item -LiteralPath $f.FullName -Force -ErrorAction Stop; $deleted++ } catch { }
            }
        }
        # Legacy IconCache.db in LocalAppData root
        $legacy = Join-Path $localApp 'IconCache.db'
        if (Test-Path $legacy) { try { Remove-Item -LiteralPath $legacy -Force -ErrorAction Stop; $deleted++ } catch { } }

        Write-Log "Icon cache repair: cleared $deleted cache file(s)." 'OK'
        # The cache files are usually locked while Explorer is running,
        # so restarting Explorer is the reliable way to force a refresh.
        try { Restart-Explorer } catch { try { Update-ExplorerIcons } catch { } }
        return $true
    } catch {
        Write-Log "Icon cache repair failed: $($_.Exception.Message)" 'WARN'
        return $false
    }
}
